# Generated by Django 5.2 on 2025-05-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('chef', 'Chef'), ('waiter', 'Waiter'), ('cleaner', 'Cleaner')], max_length=10, unique=True)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonus_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'verbose_name': 'Баға',
                'verbose_name_plural': 'Бағалар',
            },
        ),
    ]
